volumes:
  grafana:
  vm:

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro

  vm:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - vm:/victoria-logs-data
    command:
      - -storageDataPath=/victoria-logs-data
      - -retentionPeriod=100y
