name: master

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: switchbot_exporter
  IMAGE_TAG: master

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: motoki317
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/motoki317/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  scan:
    name: Scan Image Vulnerability
    runs-on: ubuntu-latest
    needs: [image]
    steps:
      - uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull ghcr.io/motoki317/${IMAGE_NAME}:${IMAGE_TAG}
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/motoki317/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
